version: '3'

services:

  broker-1:
    image: camunda/zeebe:${ZEEBE_VERSION:-latest}
    ports:
      - 51015:51015
    volumes:
      - $PWD/volumes/broker-1:/usr/local/zeebe/bin/data

  broker-2:
    image: camunda/zeebe:${ZEEBE_VERSION:-latest}
    ports:
      - 51016:51015
    volumes:
      - $PWD/volumes/broker-2:/usr/local/zeebe/bin/data
    environment:
      - "INITIAL_CONTACT_POINT=broker-1:51016"

  broker-3:
    image: camunda/zeebe:${ZEEBE_VERSION:-latest}
    ports:
      - 51017:51015
    volumes:
      - $PWD/volumes/broker-3:/usr/local/zeebe/bin/data
    environment:
      - "INITIAL_CONTACT_POINT=broker-1:51016"
